spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterAccess=1h
  application:
    name: armenian-learning-assistant
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        # Exposes the metrics and prometheus endpoints over HTTP
        include: "health,metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      # Optional: Automatically tags all metrics with your application name
      application: ${spring.application.name:armenian-learning-assistant}