spring:
  datasource:
    password: secret
    username: myuser
    url: "jdbc:postgresql://localhost:5432/mydatabase"

  ai:
    google:
      genai:
        chat:
          options:
            model: gemini-3.1-flash-lite
        api-key: ${GEMINI_API_KEY}
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            dimensions: 3072
            model: gemini-embedding-001
app:
  security:
    enabled: false # TODO, should be changed to true, when security is fully implemented
    cors:
      allowed-origins: "http://localhost:8081"
  storage:
    local:
      folder-name: ${STORAGE_FOLDER_NAME:/home/david/arm-learn-files}
  piper:
    url: http://localhost:5000
    # TODO hardcoding these properties here might not be the best choice to be honest, maybe we should get them from the webserver which we use here
    model-name: hy_AM-medium
    voice-identifier: gor-medium
logging:
  level:
    com.blbulyandavbulyan.larm: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder:
    com.blbulyandavbulyan.larm.ai.chat.advisor.LoggingProxyAdvisor: INFO