package com.blbulyandavbulyan.larm.ai.chat;

/**
 * Is thrown only in case when jakarta validation failed for the resource generated by LLM.
 */
public class UnfixableValidationException extends RuntimeException {
    public UnfixableValidationException() {
        super("Unfixable constraint validation error occurred, LLM generated bad response.");
    }
}
