package com.blbulyandavbulyan.larm.ai.chat;

import jakarta.validation.ConstraintViolationException;

/**
 * Is thrown only in case when jakarta validation failed for the resource generated by LLM.
 */
public class UnfixableValidationException extends RuntimeException {
    public UnfixableValidationException(String message) {
        super(message);
    }

    public UnfixableValidationException(ConstraintViolationException cause) {
        super(cause.getMessage(), cause);
    }
}
