package com.blbulyandavbulyan.larm.api.dialogues;

import java.util.UUID;

import com.blbulyandavbulyan.larm.api.advice.ValidationErrorResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;

@RequestMapping("/dialogues")
@Tag(name = "Dialogues", description = "Endpoints for saving Armenian dialogues generated by AI")
interface DialoguesApi {

    @PostMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(
            summary = "Save a generated dialogue",
            description =
                    """
                    Accepts a dialogue generated by /chat/dialogue. Saves all speakers, phrases \
                    (with TTS audio), and the dialogue metadata (including an embedding for \
                    semantic deduplication). Returns the ID of the created dialogue.
                    """,
            responses = {
                    @ApiResponse(
                            responseCode = "201",
                            description = "Dialogue saved successfully",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = SaveDialogueResponse.class)
                            )
                    ),
                    @ApiResponse(
                            responseCode = "400",
                            description = "Validation failed",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ValidationErrorResponse.class)
                            )
                    )
            }
    )
    SaveDialogueResponse saveDialogue(@Validated @RequestBody @Valid SaveDialogueRequest request);

    @GetMapping(value = "/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
    @Operation(
            summary = "Get a dialogue by ID",
            description = "Returns a complete dialogue including its title, speakers, and phrases.",
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "Dialogue found",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = GetDialogueResponse.class)
                            )
                    ),
                    @ApiResponse(
                            responseCode = "404",
                            description = "Dialogue not found",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ValidationErrorResponse.class)
                            )
                    )
            }
    )
    GetDialogueResponse getDialogue(@PathVariable("id") UUID id);
}
